package BYOL;

enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords.
     STUDENT, COURSE, MAJOR, SEMESTER, SCHEDULE,
     NAME, MAJOR_KEY, REQUIRED_COURSES, TITLE, CREDITS,
     YEAR, TERM, STUDENT_KEY, SEMESTER_KEY, COURSES, PRINT,
     
     
     
     EOF
}
